### ISSUE TITLE
panic in `onRaftGCLogTick`

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#247]
panic: unexpected EOF

goroutine 181 [running]:
github.com/zhangjinpeng1987/raft.(*RaftLog).Term(0xc00027f880, 0x1431, 0x1432, 0xc03d15a5e8, 0x1401)
	/Users/zhou/gopath/pkg/mod/github.com/zhangjinpeng1987/raft@v0.0.0-20190624145930-deeb32d6553d/log.go:267 +0x1e4
github.com/ngaut/unistore/tikv/raftstore.(*peerFsmDelegate).onRaftGCLogTick(0xc03d17be90)
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/fsm_peer.go:1155 +0x4a0
github.com/ngaut/unistore/tikv/raftstore.(*peerFsmDelegate).onTick(0xc03d17be90)
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/fsm_peer.go:196 +0x176
github.com/ngaut/unistore/tikv/raftstore.(*peerFsmDelegate).handleMsgs(0xc03d17be90, 0xc03d17bea0, 0x1, 0x1)
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/fsm_peer.go:146 +0x656
github.com/ngaut/unistore/tikv/raftstore.(*raftWorker).run(0xc0141e0d20, 0xc0000ae1e0, 0xc00014c130)
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/peer_state.go:153 +0x9b9
created by github.com/ngaut/unistore/tikv/raftstore.(*raftBatchSystem).startSystem
	/Users/zhou/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/fsm_store.go:523 +0x160

**Comment by coocood** [comment]
Encountered during prepare sysbench 1 table, size 10000000

**Comment by coocood** [comment]
This is caused by an unrelated change:
```
ac.wbLastBytes = 0
```

modify the position of field `lastAppliedIndex` fixes the problem.

Seems like a bug in Go.

**Comment by coocood** [comment]
encountered again, need further investigation

**Comment by coocood** [comment]
The raft log retrieved from badger unable to unmarshal to entry.
The value changed from size 156088 to 25016, it seems the data is corrupt.

**Comment by coocood** [comment]
new evident log

The value put into the DB has changed intantly when Get from it. The number 17115769815617758903 is the hash value of the key.
```
2019/10/31 14:19:17.868424 writer.go:240: [info] [key:3063800065772907509 valLen:62934 key:15574274095066835190 valLen:258556 key:17115769815617758903 valLen:265832 key:9065245261705916547 valLen:265832]
2019/10/31 14:19:17.897541 transaction.go:368: [info] txn get key:17115769815617758903, valSize:3688
2019/10/31 14:19:17.897567 peer_storage.go:750: [error] failed unmarshal entry key (10:3178), value 8219962194789243310, size 3688
panic: unexpected EOF
```

**Comment by coocood** [comment]
issue addressed, it's caused by value size exceeds MaxUint16, but the `ValueStruct.EncodedSize` returns a uint16 value.

**Comment by coocood** [comment]
https://github.com/coocood/badger/pull/135
