### ISSUE TITLE
Write batch to kv leads to panic

### ISSUE THREAD

**Issue by cfzjywxk** [ngaut/unistore#268]
After stop and restart the node process,  some node process crashes

```
panic: failed to delete key

goroutine 147 [running]:
github.com/ngaut/unistore/tikv/raftstore.(*WriteBatch).WriteToKV(0xc000030ae0, 0xc00000e160, 0x44fcc8, 0x39db729ba1720)
	/home/rwork/go/src/github.com/pingcap/unistore/tikv/raftstore/engine.go:255 +0x56d
github.com/ngaut/unistore/tikv/raftstore.(*applyContext).writeToDB(0xc000134b40)
	/home/rwork/go/src/github.com/pingcap/unistore/tikv/raftstore/applier.go:344 +0x123
github.com/ngaut/unistore/tikv/raftstore.(*applyContext).flush(0xc000134b40)
	/home/rwork/go/src/github.com/pingcap/unistore/tikv/raftstore/applier.go:405 +0x63
github.com/ngaut/unistore/tikv/raftstore.(*raftWorker).runApply(0xc000030b40, 0xc000040130)
	/home/rwork/go/src/github.com/pingcap/unistore/tikv/raftstore/peer_state.go:265 +0x172
created by github.com/ngaut/unistore/tikv/raftstore.(*raftWorker).run
	/home/rwork/go/src/github.com/pingcap/unistore/tikv/raftstore/peer_state.go:122 +0x64
```

**Comment by coocood** [comment]
Fixed by https://github.com/ngaut/unistore/pull/288
