### ISSUE TITLE
panic on raft db

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#487]
```
unexpected fault address 0x7f5aafdcbb3e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f5aafdcbb3e pc=0xfe0362]

goroutine 130 [running]:
runtime.throw(0x19ce2c6, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc096fd8c88 sp=0xc096fd8c58 pc=0x4384f2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0xc096fd8cc0 sp=0xc096fd8c88 pc=0x44fc48
github.com/golang/snappy.decode(0x7f5aafdcbb3e, 0x872d, 0x8800, 0xc7ba8cf803, 0x400f, 0x43fd, 0x0)
	/Users/evan/gorepo/pkg/mod/github.com/golang/snappy@v0.0.1/decode_amd64.s:131 +0x82 fp=0xc096fd8d00 sp=0xc096fd8cc0 pc=0xfe0362
github.com/golang/snappy.Decode(0x7f5aafdcbb3e, 0x872d, 0x8800, 0xc7ba8cf800, 0x4012, 0x4400, 0x0, 0x9620000, 0xc7ba8cf800, 0xc096fd8e08, ...)
	/Users/evan/gorepo/pkg/mod/github.com/golang/snappy@v0.0.1/decode.go:65 +0xeb fp=0xc096fd8d58 sp=0xc096fd8d00 pc=0xfdfc4b
github.com/pingcap/badger/options.CompressionType.Decompress(0xc300000001, 0xc7ba8cf800, 0x4012, 0x4400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/options/options.go:78 +0x425 fp=0xc096fd8f18 sp=0xc096fd8d58 pc=0x100bd45
github.com/pingcap/badger/table/sstable.(*Table).loadBlock(0xc36def6300, 0x5c, 0xc539c54720, 0xc000700000, 0x412bdb, 0xc096fd9058)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/sstable/table.go:502 +0x156 fp=0xc096fd8fe0 sp=0xc096fd8f18 pc=0x102e7d6
github.com/pingcap/badger/table/sstable.(*Table).block.func1(0x186b240, 0x4be8886b, 0xc0d3829530, 0xc096fd90a0, 0x10237b8)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/sstable/table.go:469 +0x45 fp=0xc096fd9020 sp=0xc096fd8fe0 pc=0x102fa65
github.com/pingcap/badger/cache.(*Cache).compute(0xc00012e0c0, 0xc0d3829530, 0xc096fd9160, 0x0, 0x0, 0x0, 0x0, 0xc096fd9100)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/cache/cache.go:225 +0xd7 fp=0xc096fd90b0 sp=0xc096fd9020 pc=0x101f1f7
github.com/pingcap/badger/cache.(*Cache).GetOrCompute(0xc00012e0c0, 0x6f3e0000005c, 0xc096fd9160, 0xc096fd9218, 0xc096fd9160, 0xd17260cf0802adfc, 0xce1ea6)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/cache/cache.go:207 +0xa5 fp=0xc096fd9110 sp=0xc096fd90b0 pc=0x101f065
github.com/pingcap/badger/table/sstable.(*Table).block(0xc36def6300, 0x5c, 0xc539c54720, 0xc53a570000, 0xc096fd9218, 0x1025131)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/sstable/table.go:468 +0xd5 fp=0xc096fd9190 sp=0xc096fd9110 pc=0x102e495
github.com/pingcap/badger/table/sstable.(*Iterator).next(0xc52b9858c0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/sstable/iterator.go:379 +0xc5 fp=0xc096fd91e0 sp=0xc096fd9190 pc=0x102ae65
github.com/pingcap/badger/table/sstable.(*Iterator).next(0xc52b9858c0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/sstable/iterator.go:394 +0x1c5 fp=0xc096fd9230 sp=0xc096fd91e0 pc=0x102af65
github.com/pingcap/badger/table/sstable.(*Iterator).Next(0xc52b9858c0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/sstable/iterator.go:446 +0x47 fp=0xc096fd9248 sp=0xc096fd9230 pc=0x102b327
github.com/pingcap/badger/table.(*ConcatIterator).Next(0xc533f59680)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/concat_iterator.go:101 +0x38 fp=0xc096fd9268 sp=0xc096fd9248 pc=0x100c738
github.com/pingcap/badger/table.(*MergeIterator).Next(0xc551392ba0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/table/merge_iterator.go:93 +0x52 fp=0xc096fd9280 sp=0xc096fd9268 pc=0x100cd12
github.com/pingcap/badger/y.NextAllVersion(0x1da6838, 0xc551392ba0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/y/iterator.go:113 +0x56 fp=0xc096fd92a0 sp=0xc096fd9280 pc=0xce2176
github.com/pingcap/badger.CompactTables(0xc5387d7000, 0xc522123800, 0xc551392b70, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/levels.go:436 +0x14d fp=0xc096fd9648 sp=0xc096fd92a0 pc=0x1054f4d
github.com/pingcap/badger.(*localCompactor).compact(0x2b2a5d0, 0xc5387d7000, 0xc522123800, 0xc551392b70, 0x0, 0xc096fd96f0, 0x46f3db, 0x1d2f049c3e3c9, 0xc71768261b)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/compaction.go:499 +0x3f fp=0xc096fd9698 sp=0xc096fd9648 pc=0x10419bf
github.com/pingcap/badger.(*levelsController).compactBuildTables(0xc00025db20, 0xc5387d7000, 0x2af9680, 0x1057f3d, 0x21a0256, 0x63, 0x297)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/levels.go:395 +0xc2 fp=0xc096fd9728 sp=0xc096fd9698 pc=0x1054be2
github.com/pingcap/badger.(*levelsController).runCompactDef(0xc00025db20, 0xc5387d7000, 0xc5387ee980, 0x0, 0x0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/levels.go:608 +0x933 fp=0xc096fd9a30 sp=0xc096fd9728 pc=0x10579d3
github.com/pingcap/badger.(*levelsController).doCompact(0xc00025db20, 0x1, 0x3ff878d06bbdbe3c, 0xc5387ee980, 0x0, 0x0, 0x0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/levels.go:664 +0x489 fp=0xc096fd9ee0 sp=0xc096fd9a30 pc=0x1057f69
github.com/pingcap/badger.(*levelsController).runWorker(0xc00025db20, 0xc00019c090, 0x0)
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/levels.go:201 +0xcf fp=0xc096fd9fc8 sp=0xc096fd9ee0 pc=0x1053aaf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc096fd9fd0 sp=0xc096fd9fc8 pc=0x472001
created by github.com/pingcap/badger.(*levelsController).startCompact
	/Users/evan/gorepo/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20210331054718-0885bbfa8520/levels.go:180 +0x93
```

**Comment by coocood** [comment]
encountered again, try to avoid it by disabling compression.

**Comment by coocood** [comment]
since raft db has been replaced by raft engine, this issue is obsolete.
