### ISSUE TITLE
panic on recover

### ISSUE THREAD

**Issue by coocood** [ngaut/unistore#489]
panic: runtime error: index out of range [-55]

goroutine 1 [running]:
github.com/ngaut/unistore/sdb.atomicRemoveL0(0xc000870270, 0x37, 0x2)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/sdb/flush.go:203 +0x30d
github.com/ngaut/unistore/sdb.(*DB).applyCompaction(0xc01d9ec6c0, 0xc000870270, 0xc056e87080, 0xc02d21acc0, 0x0, 0x0)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/sdb/compaction.go:910 +0x5d8
github.com/ngaut/unistore/sdb.(*DB).ApplyChangeSet(0xc01d9ec6c0, 0xc056e87080, 0x0, 0x0)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/sdb/compaction.go:830 +0x1aa
github.com/ngaut/unistore/tikv/raftstore.(*RecoverHandler).Recover(0xc00018cf40, 0xc01d9ec6c0, 0xc000870270, 0xc01d0b1f80, 0x0, 0x0, 0x0)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/tikv/raftstore/recover.go:97 +0x698
github.com/ngaut/unistore/sdb.(*DB).loadShards(0xc01d9ec6c0, 0xc000040b70, 0xe)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/sdb/db.go:356 +0x182
github.com/ngaut/unistore/sdb.OpenDB(0xc0008680d8, 0x13, 0x1e84800, 0x10, 0x5, 0xa, 0x3b9aca000, 0x1000000, 0x3, 0x0, ...)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/sdb/db.go:113 +0x56d
github.com/ngaut/unistore/server.createKVDB(0x19cd352, 0x2, 0xc00018e280, 0xc00012c840, 0x1d6b040, 0xc0004848d0, 0xc00018cf40, 0xc00003d6e8, 0x0, 0x0, ...)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/server/server.go:143 +0x2bd
github.com/ngaut/unistore/server.New(0xc00003d680, 0x1dac8d8, 0xc000538480, 0x0, 0x0, 0x1dac8d8)
	/Users/evan/gorepo/src/github.com/ngaut/unistore/server/server.go:50 +0x3d9
main.main()
	/Users/evan/gorepo/src/github.com/ngaut/unistore/cmd/unistore-server/main.go:131 +0x607

**Comment by coocood** [comment]
The reason is that the deduplicate algorithm is not reliable, if the are several rounds of compaction done to a shard, we can not detect the duplication.

**Comment by coocood** [comment]
Fixed by https://github.com/ngaut/unistore/pull/498
