### ISSUE TITLE
panic on sharding db

### ISSUE THREAD

**Issue by hslam** [ngaut/unistore#526]
```
unexpected fault address 0x477df2d4
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x477df2d4 pc=0x4c74710]

goroutine 11152 [running]:
runtime.throw(0x5670cea, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0284c1348 sp=0xc0284c1318 pc=0x403aa92
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:749 +0x3e5 fp=0xc0284c1378 sp=0xc0284c1348 pc=0x4051465
github.com/ngaut/unistore/sdb/table/sstable.(*Table).loadBlock(0xc009536cb0, 0x0, 0x2, 0xc00f741950, 0xc00f741900)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/table/sstable/table.go:190 +0x50 fp=0xc0284c13c0 sp=0xc0284c1378 pc=0x4c74710
github.com/ngaut/unistore/sdb/table/sstable.(*Iterator).seekToFirst(0xc0004cfe00)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/table/sstable/iterator.go:199 +0xcc fp=0xc0284c1448 sp=0xc0284c13c0 pc=0x4c6faac
github.com/ngaut/unistore/sdb/table/sstable.(*Iterator).Rewind(0xc0004cfe00)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/table/sstable/iterator.go:468 +0x47 fp=0xc0284c1460 sp=0xc0284c1448 pc=0x4c72007
github.com/ngaut/unistore/sdb/table.(*MergeIterator).Rewind(0xc025f9b2f0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/table/merge_iterator.go:159 +0x3b fp=0xc0284c1478 sp=0xc0284c1460 pc=0x4c633db
github.com/ngaut/unistore/sdb/table.(*MergeIterator).Rewind(0xc025f9b380)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/table/merge_iterator.go:159 +0x3b fp=0xc0284c1490 sp=0xc0284c1478 pc=0x4c633db
github.com/ngaut/unistore/sdb/table.(*MergeIterator).Rewind(0xc025f9b470)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/table/merge_iterator.go:159 +0x3b fp=0xc0284c14a8 sp=0xc0284c1490 pc=0x4c633db
github.com/ngaut/unistore/sdb.newCompactL0Helper(0xc000146480, 0xc012abf320, 0xc000209240, 0x0, 0x0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/compaction.go:358 +0x35c fp=0xc0284c1580 sp=0xc0284c14a8 pc=0x4c963bc
github.com/ngaut/unistore/sdb.(*DB).compactL0(0xc000146480, 0xc012abf320, 0xc0007bfa70, 0x0, 0x0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/compaction.go:441 +0x52f fp=0xc0284c1738 sp=0xc0284c1580 pc=0x4c9746f
github.com/ngaut/unistore/sdb.(*DB).Compact(0xc000146480, 0xffffffffffffffff, 0x0, 0x3ff758146770a3d7, 0xc012abf320, 0x0, 0x0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/compaction.go:604 +0x651 fp=0xc0284c1e50 sp=0xc0284c1738 pc=0x4c98b31
github.com/ngaut/unistore/sdb.(*DB).runCompactionLoop.func1(0xc000146480, 0xffffffffffffffff, 0x0, 0x3ff758146770a3d7, 0xc012abf320, 0xc00039a060, 0xc000040080)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/compaction.go:511 +0x79 fp=0xc0284c1fa8 sp=0xc0284c1e50 pc=0x4cb96f9
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0284c1fb0 sp=0xc0284c1fa8 pc=0x4073321
created by github.com/ngaut/unistore/sdb.(*DB).runCompactionLoop
	/Users/huangmeng/go/src/github.com/ngaut/unistore/sdb/compaction.go:510 +0x191
```

**Comment by coocood** [comment]
it's a bug on a WIP PR.
