### ISSUE TITLE
panic on event handler

### ISSUE THREAD

**Issue by hslam** [ngaut/unistore#570]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x163cb33]

goroutine 133 [running]:
github.com/ngaut/unistore/tikv.(*RaftRegionManager).runEventHandler(0xc15177d8c0)
        /Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/region.go:413 +0x3b3
created by github.com/ngaut/unistore/tikv.NewRaftRegionManager
        /Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/region.go:296 +0x158
```

**Comment by hslam** [comment]
During data migration, the cluster is stopped when some regions is applying the snapshot. These regions will not be registered to the region manager when the cluster is restarted. The panic will occur if these regions are read. These regions in the applying state should also be registered to the region manager.

**Comment by hslam** [comment]
Fixed by https://github.com/ngaut/unistore/pull/580
