### ISSUE TITLE
panic when multiple new stores are started almost simultaneously

### ISSUE THREAD

**Issue by hslam** [ngaut/unistore#595]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xcc pc=0x120cb21]

goroutine 1 [running]:
github.com/ngaut/unistore/engine.(*Shard).IsInitialFlushed(...)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/engine/shard.go:369
github.com/ngaut/unistore/tikv/raftstore.(*raftBatchSystem).loadPeers.func1(0x5, 0xc0003b41b0, 0x9, 0x9, 0xc0003b41a0, 0x10, 0x10, 0x0, 0x0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/fsm_store.go:251 +0x2e1
github.com/ngaut/unistore/raftengine.(*Engine).IterateAllStates.func1(0x1d690a0, 0xc000453700, 0x1)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/raftengine/engine.go:264 +0x8a
github.com/google/btree.(*node).iterate(0xc0002c8480, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0xc025420000, 0xc0005ab4b8, 0x60f688dc)
	/Users/huangmeng/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:557 +0x1ec
github.com/google/btree.(*BTree).Descend(...)
	/Users/huangmeng/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:813
github.com/ngaut/unistore/raftengine.(*Engine).IterateAllStates(0xc0003dd320, 0x79d6fc01, 0xc0005ab710, 0x5c, 0x0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/raftengine/engine.go:268 +0xcc
github.com/ngaut/unistore/tikv/raftstore.(*raftBatchSystem).loadPeers(0xc00046d590, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/fsm_store.go:218 +0x28f
github.com/ngaut/unistore/tikv/raftstore.(*raftBatchSystem).start(0xc00046d590, 0xc000128378, 0xc00015c1c0, 0xc0000fc840, 0xc0000fc940, 0x1db3938, 0xc000460300, 0xc00046d170, 0x1da7d98, 0xc000407860, ...)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/fsm_store.go:352 +0x5ef
github.com/ngaut/unistore/tikv/raftstore.(*Node).startNode(0xc00047f360, 0xc0000fc840, 0xc0000fc940, 0xc00046d170, 0x0, 0x0)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/node.go:243 +0x17c
github.com/ngaut/unistore/tikv/raftstore.(*Node).Start(0xc00047f360, 0x1d9f788, 0xc00003e0a0, 0xc0000fc840, 0xc0000fc940, 0xc00046d170, 0xc0000fc880, 0xc00047f360, 0xc0000f4000)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/node.go:92 +0x2e8
github.com/ngaut/unistore/tikv/raftstore.(*InnerServer).Start(0xc000128360, 0x1db3938, 0xc000460300, 0xc000407860, 0x1da7e28)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/raftstore/server.go:145 +0x15a
github.com/ngaut/unistore/tikv.NewServer(0xc0001be000, 0x1db3938, 0xc000460300, 0x0, 0x0, 0x1db3938)
	/Users/huangmeng/go/src/github.com/ngaut/unistore/tikv/server.go:107 +0x5d3
main.main()
	/Users/huangmeng/go/src/github.com/ngaut/unistore/cmd/unistore-server/main.go:151 +0x686
```

**Comment by hslam** [comment]
When a new store bootstraps a cluster that is already bootstrapped, if the first region of this store is not the same as the first region of the cluster, we should remove the first region and clean up all of its states. Panic caused by not completely cleaning up the state of the first region.
```
08.610 [node.go:197] ["alloc first region id, regionID: 5, clusterID: 6986922348229533022, storeID: 4"]
08.611 [node.go:202] ["alloc first peer id for first region, peerID: 6, regionID: 5"]
08.611 [shard.go:132] ["ingest shard 5:1 maxMemTblSize 16000000, commitTS 0"]
08.613 [node.go:81] ["try bootstrap cluster, storeID: 4, region: id:5 region_epoch:<conf_ver:1 version:1 > peers:<id:6 store_id:4 > "]
08.616 [node.go:233] ["cluster is already bootstrapped, clusterID: 6986922348229533022"]
08.616 [engine.go:721] ["remove shard 5"]
08.625 [node.go:242] ["start raft store node, storeID: 4"]
08.625 [fsm_peer.go:72] ["region 5:1 create peer with ID 6"]
08.625 [peer_storage.go:290] ["region 5:1 init raft state"]
```

**Comment by hslam** [comment]
Fixed by https://github.com/ngaut/unistore/pull/597
